package com.example.demo.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import io.swagger.annotations.ApiModelProperty;

@Entity
public class Item {

	@Id
	@GeneratedValue
	@ApiModelProperty(notes="Item number is autogenerated")
	private long itemNo;
	
	@ApiModelProperty(notes="Item's name")
	@NotEmpty(message = "Please provide a name")
	private String name;
	
	@ApiModelProperty(notes="Item amount in inventory")
	@NotNull(message = "Please provide an amount")
	private long amount;
	
	@ApiModelProperty(notes="Item's inventory code")
	@NotEmpty(message = "Please provide an inventory code")
	private String inventoryCode;
	
	
	@Override
	public String toString() {
		return "Item [itemNo=" + itemNo + ", name=" + name + ", amount=" + amount + ", inventoryCode=" + inventoryCode
				+ "]";
	}
	public long getItemNo() {
		return itemNo;
	}
	public void setItemNo(long itemNo) {
		this.itemNo = itemNo;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public long getAmount() {
		return amount;
	}
	public void setAmount(long amount) {
		this.amount = amount;
	}
	public String getInventoryCode() {
		return inventoryCode;
	}
	public void setInventoryCode(String inventoryCode) {
		this.inventoryCode = inventoryCode;
	}
}
